### ISSUE TITLE
You don't test that `driverId` is inaccessible

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-advanced-scope-closures-lab#4]

**Comment by JeffKatzy** [comment]
This I can't figure out to test.  If someone properly keeps it out of scope, and I try to reference it that does not exist in the test, JavaScript throws a referenceerror in the test, and tests break.  Cannot do window.driverId because with let, not defined on window.

**Comment by jmburges** [comment]
oh good point. KK HONOR SYSTEM
