### ISSUE TITLE
Can pass local tests without creating driver function

### ISSUE THREAD

**Issue by dschlauderaff** [learn-co-curriculum/js-advanced-scope-closures-lab#5]
Until the following code is placed in index.js:

function createDriver(){}

the createDriver test give the following error on localhost page console:

indexTest.js:35 Uncaught ReferenceError: createDriver is not defined
    at Suite.<anonymous> (indexTest.js:35)
    at Object.create (mocha.js:931)
    at context.describe.context.context (mocha.js:744)
    at Suite.<anonymous> (indexTest.js:34)
    at Object.create (mocha.js:931)
    at context.describe.context.context (mocha.js:744)
    at indexTest.js:3

the createDriver test never appears on localhost and allow the lab to pass local tests with just produceDrivingRange and produceTipCalculator

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
