### ISSUE TITLE
The test for createDriver() doesn't show in the browser

### ISSUE THREAD

**Issue by jljardon** [learn-co-curriculum/js-advanced-scope-closures-lab#8]
The test for the last function doesn't show in the browser and the lab is marked as 100% complete without it: 

![screen shot](https://imgur.com/XKSn32g.png)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
